apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-lb
  labels:
    tier: sep-backend
  annotations:
    service.beta.kubernetes.io/ovh-loadbalancer-proxy-protocol: "v1"
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: sep-backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
