apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-filestash
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestash
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: filestash
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-filestash
        image: machines/filestash:d8fe013
        resources:
          limits:
            memory: 32Mi
            cpu: 50m
          requests:
            memory: 16Mi
            cpu: 10m
        env:
          - name: FILESTASH_DOMAIN
            valueFrom:
              secretKeyRef:
                name: sep-backend-filestash-secret
                key: domain
