apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-filestash-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: filestash
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 8334
    name: filestash
