apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-discord
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-discord
        image: singouins/discord:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 50m
          requests:
            memory: 64Mi
            cpu: 10m
        env:
        - name: SEP_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: sql-user
        - name: SEP_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: sql-pass
        - name: SEP_MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: sql-db
        - name: SEP_MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: sql-host
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: token
        - name: PYTHONUNBUFFERED
          value: 'True'
        - name: PYTHONIOENCODING
          value: 'UTF-8'
