apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-metrics-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: metrics
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 8008
    name: metrics
